service: ve-agent-backend

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, 'your_openai_api_key_here'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  chat:
    handler: lambda_handler.handler
    events:
      - http:
          path: /chat/stream
          method: post
          cors: true
      - http:
          path: /health
          method: get
          cors: true
      - http:
          path: /
          method: get
          cors: true
    timeout: 30
    memorySize: 1024

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false
    fileName: requirements-lambda.txt
